- type: job
  id: BladeGuardian
  name: job-name-bladeguardian
  description: job-description-bladeguardian
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 28800 #8 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #50 hrs
  weight: 10
  startingGear: BladeGuardianGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BladeGuardianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficerBlack
    back: ClothingBackpackERTSecurity
    head: ClothingHeadCapCentcomBlack
    neck: ClothingNeckCloakCentcomBlack
    outerClothing: ClothingOuterArmorBasic
    shoes: ClothingShoesSwat
    id: BladeGuardianPDA
    ears: ClothingHeadsetCentCom
    eyes: ClothingEyesGlassesSecurity
  storage:
    back:
    - BoxSurvival
    - EnergySword

- type: entity
  parent: CentcomIDCard
  id: BladeGuardianIDCard
  name: ID карта Стража Клинка
  components:
  - type: Sprite
    layers:
    - state: gold
    - state: ert_commander
  - type: IdCard
    jobTitle: "Страж Клинка"
  - type: Item
    heldPrefix: gold # Какого хуя
